### ISSUE TITLE
Consider haystack 2.7 when released

### ISSUE THREAD

**Issue by r-leyshon** [ministryofjustice/rd-search-backend#16]
On executing `pytest`, warning generated:

```
=================================================== warnings summary ===================================================
search-backend-env/lib/python3.10/site-packages/haystack/core/errors.py:34
  /Users/richard.leyshon/Documents/GitHub/MoJ/rd-search-backend/search-backend-env/lib/python3.10/site-packages/haystack/core/errors.py:34: DeprecationWarning: PipelineMaxLoops is deprecated and will be remove in version '2.7.0'; use PipelineMaxComponentRuns instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
haystack warning - [see here](https://github.com/deepset-ai/haystack/issues/8452 ),  incrementing to haystack 2.7 should get rid of this when it's released (still on 2.6.1 for now)

_Originally posted by @r-leyshon in https://github.com/ministryofjustice/rd-search-backend/pull/15#discussion_r1808834810_

**Comment by chloepugh** [comment]
Addressed in [this commit](https://github.com/ministryofjustice/rd-search-backend/commit/1d758a1ddd498f93eb92a58d72c0407760c0db1d)
